---
title: "Bubble_plot"
author: "Sergio E. Morales"
date: "September 8 2016"
output:
pdf_document:
fig_caption: yes
fig_height: 7
fig_width: 7
---

###Calculation of mean, SE, SD and CI from phyloseq processed data and plotting as bubble plot

#####Code is intended for use with melted datasets from phyloseq. It should work or any other data.frame but this example uses a processed phyloseq dataset. Data used here is found in the folder.
```{r load libraries}
library(knitr)
```

```{r global_options, echo=FALSE, results='hide'}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.align='center', results='hide', echo=TRUE, warning=FALSE, message=FALSE)
```

```{r Load melted data.frame}
Fs <- read.csv("/Users/sergiomorales/Documents/NZResearch/R_Code/Line_graphs_w_errorbars/FINALshort.csv",fill = TRUE, header = TRUE, sep = ",")
```

```{r Summarize data and calcuate SE SD CI mean}
library(Rmisc)
# summarySE provides the mean standard deviation, standard error of the mean, and a (default 95%) confidence interval
# In this example the mean will be calculated from the Abundance column by all the variables listed in groupvars.
tgc <- summarySE(Fs, measurevar="Abundance", groupvars=c("Treatment","Day","OTU", "Treatment1", "Treatment2", "Phylum"))
tgc
```

```{r Create bubble plot}
library(ggplot2)

dodge <- position_dodge(width=0.5)  # move dots .01 to the left and right to avoid overlap
ggplot(tgc, aes(x=Day, y=OTU, colour=Phylum, group=Treatment)) +
  geom_point(aes(size=Abundance))  +
  scale_size_continuous() + 
  facet_grid(Treatment2 ~ Treatment1, drop = TRUE, space = "fixed", scales = "free") + # facet by One variable on y axis and a second variable on the x axis
  theme_bw() + # make background white
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())  # remove gridlines

```

```{r save plot}
ggsave("/Users/sergiomorales/Downloads/p.pdf",width=8,height=12)
```
